# Generated by Django 4.0.6 on 2022-07-27 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='main_app.tags'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
